[phases.setup]
nixPkgs = ["nodejs_22", "npm-10_x", "openssl"]

[variables]
NODE_VERSION = "22.12.0"

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build", "npx prisma generate"]

[start]
cmd = "npm start"

