[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x", "openssl"]

[phases.install]
cmds = ["rm -rf node_modules/.cache || true", "npm ci"]

[phases.build]
cmds = ["npm run build", "npx prisma generate"]

[start]
cmd = "npm start"

